### ISSUE TITLE
Spray can adds flooring textures to beds

### ISSUE THREAD

**Issue by Asterisk555** [Floogen/AlternativeTextures#41]
If you right click flooring and add textures to the spray can, those textures won't work on floors but they will instead affect other furniture and add floor textures as bed textures (for example)

smapi log:
https://smapi.io/log/4b09ef5db3cb430bb34b760563b11099

Screenshots:
https://postimg.cc/p9t3Bs52
https://postimg.cc/gwqQt333

**Comment by Floogen** [comment]
This is fixed with AT v6.4.3, though you may need to delete the affected beds or use a Paint Brush to copy a valid texture over to them.
