### ISSUE TITLE
[AT] Update to Stardew Valley v1.6

### ISSUE THREAD

**Issue by Floogen** [Floogen/AlternativeTextures#53]
Most prefix patches should be fine barring any drastic changes to the draw logic. Transpilers may need to be rewritten.

**Comment by Floogen** [comment]
Need to handle new item ID assignment and building changes.

**Comment by tlitookilakin** [comment]
the `performObjectDropInAction` patch in `FencePatch` has a null method on startup with the most recent 1.6 alpha and AT alpha 10. It looks like the method has an additional bool parameter on the end of it now, which means AT can't find it.

**Comment by Floogen** [comment]
I fixed this yesterday with [b831080](https://github.com/Floogen/AlternativeTextures/commit/b83108008052caeaa13f84d6994767d213a96cc6), but I had not pushed the changes yet.

I will have the fixed deploy later today.

Thank you for letting me know!
