### ISSUE TITLE
Per SMAPI - Error with AT - Issue with Harmony Patching

### ISSUE THREAD

**Issue by DozyDew** [Floogen/AlternativeTextures#58]
Alternative Textures 7.0.0-alpha.10- Version 7.0.0-alpha.10

When SMAPI is loading in, the following error is listed for Alternative Textures. This occurs even when no other mods, aside from Alternative Textures, are in the mods folder.
SMAPI log parser link: https://smapi.io/log/624d6750897d4a30b04ecf02664579aa

When this was posted to Trello (1.6 alpha board), one other person commented saying they are encountering the same error. 

I love using AT, so am hoping a fix is figured out for this issue soon.

**Comment by Floogen** [comment]
This had been fixed with [b831080](https://github.com/Floogen/AlternativeTextures/commit/b83108008052caeaa13f84d6994767d213a96cc6), but I did not have the time needed until now to push out the update.

See the v7.0.0-alpha.11 for the fix.
