### ISSUE TITLE
1.6 - SMAPI Error When Loading Save With AT In Use

### ISSUE THREAD

**Issue by DozyDew** [Floogen/AlternativeTextures#59]
Hey there Floogen,

Thank you very much for fixing the last bug I reported :)  I replaced the previous version with your newest release (Alternative Textures 7.0.0-alpha.11).

Unfortunately, a new error now occurs when attempting to load a previous save file with AT textures in use.  

**When Error Does Not Occur**: I did _not_ encounter this error when loading in a previous save file that did not have any AT textures in use (although, that save file was only a few days into Spring, Year 1). I was also able to utilize AT to change textures for several furniture items within this save with no issues encountered.

**When Error Does Occur**: The error occurs after clicking on a save file that does have AT textures in use. The save seems to be loading for a bit, but then the error occurs and the I am returned to the main menu.

 [Here is a link to the SMAPI Error Log](https://smapi.io/log/d966f4ebf2794776992db1eddb98856a)

If there is any additional information that I can provide that would be helpful, please let me know.

Thank you, again, for creating and maintaining this incredible mod.

**Comment by Floogen** [comment]
Fixed with v7.0.0-alpha.12.

Thank you for reporting that issue!

**Comment by DozyDew** [comment]
No problem!
